apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: trainer-prod
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/MLops-Project-Platform/mlops-helm-charts.git
    targetRevision: main
    path: charts/trainer-job
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: mlops
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
